### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by elfassy** [nakajima/jquery-livesearch#1]
The seach results should be case insensitive (ie, searching "a" should return "All")

.toLowerCase()

**Comment by elfassy** [comment]
Solution:

add this to the top of the file:
       $.extend($.expr[':'], {
          'containsi': function(elem, i, match, array)
          {
           return (elem.textContent || elem.innerText || '').toLowerCase()
          .indexOf((match[3] || "").toLowerCase()) >= 0;
          }
       });

then change :contains to :containsi

**Comment by nakajima** [comment]
Done. Thanks!
